FROM node:20-alpine

WORKDIR /app

# Copia apenas package.json para permitir cache de build
COPY package.json package-lock.json* ./

# Instala dependências (vai instalar dentro do volume se ele existir no compose)
RUN npm install --production

# Agora copia o restante do código
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
